sudo: required
language: python
services:
  - docker
  - postgresql
addons:
  postgresql: '9.6'

before_install:
  - docker build -t untangled-be -f Dockerfile.test .

before_script:
- psql --version
- psql -c 'create database untangled_test;' -U postgres
- python manage.py db upgrade

script:
  - pytest

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Untangled-BE"
  env: "Untangledbe-env"
  bucket_name: "elasticbeanstalk-us-east-2-725149889425"
  bucket_path: "Untangled-BE"
  on:
    branch: docker-production
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

