language: python
python:
- '3.9.1'
services:
- postgresql
addons:
  postgresql: '9.6'
install:
- pip install -r requirements.txt
before_script:
- psql --version
- psql -c 'create database untangled_test;' -U postgres
- python manage.py db upgrade
script:
- pytest
# deploy:
#   provider: heroku
#   api_key:
#     secure:
#   app: untangled-be
#   on:
#     repo: 2008-Untangled/Untangled-BE
#     branch: main
#   skip_cleanup: 'true'
#   run:
#     - pip install -r requirements.txt
#     - python manage.py db upgrade
