version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - db
    networks:
      - default
    ports:
      - 5000:5000
    restart: always

  
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    networks:
      - default
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=untangled_dev

 # Create tables and seed database
 
 # cat untangled_dev.sql | docker exec -i 24ec43736f92 psql --username=username --dbname=untangled_dev
