"""empty message

Revision ID: e6c9e7eb2925
Revises: 8ef4ced83c92
Create Date: 2021-02-27 17:39:14.481436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c9e7eb2925'
down_revision = '8ef4ced83c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('x', sa.Integer(), nullable=True))
    op.add_column('memories', sa.Column('y', sa.Integer(), nullable=True))
    op.drop_column('memories', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('location', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('memories', 'y')
    op.drop_column('memories', 'x')
    # ### end Alembic commands ###
